### PR TITLE
rrricanes

### PR DESCRIPTION
**Pull request by timtrice**
Submitting rrricanes blog post.

## Description

Describe core functions of obtaining NHC text/GIS datasets.

## Related Issue

[Onboarding #118](https://github.com/ropensci/onboarding/issues/118)

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Thanks for the pull request @timtrice. Does this mean the NHC site is good to go? or is the post ready, but on hold? I currently have your post scheduled to be published on Tues Sept 26.

**Comment by timtrice** [comment]
They emailed this afternoon it was resolved. All of my Travis and Appveyor tests are passing. The Rmd was rendered, the post is ready. So, at least for this brief moment in time I think I'm all set. :)

**Comment by sckott** [comment]
@timtrice i can't reproduce some of the post. 

There's a code chunk that gives me an error 

```r
gis <- gis_wsp(
  datetime = strftime(d - 60 * 60 * 3, format = "%Y%m%d%H", tz = "UTC"), 
  res = 5) %>% 
  gis_download()

#> trying URL 'http://www.nhc.noaa.gov/gis/'
#> downloaded 35 KB
#> 
#> Error in utils::unzip(zip_file, list = TRUE) : 
#>   zip file '/var/folders/gs/4khph0xs0436gmd2gdnwsg080000gn/T//RtmpRrHddS/file93095c72a62' cannot #> be opened
```

thoughts?

**Comment by sckott** [comment]
@timtrice also, i'm going to use a rendered .md instead of the self contained html, just fyi

**Comment by timtrice** [comment]
@sckott , 

This is what is returned from the `gis_wsp` call:

> ERROR: The request could not be satisfied\nERROR\nThe request could not be satisfied.\n\nThis distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.\n\nGenerated by cloudfront (CloudFront)\nRequest ID: xK6F9OQJUPyXkzwlKxqiL6_4Pm6RLdPp0mu5_UizHs9QEBFlMm5hbg==\n\n\n\n"

This is the exact same error that I was getting a few weeks ago that, at one point, had been resolved. 

One difference I see is now they're using GET parameters in the URL instead of POST (see line 439 in the [gis_wsp](https://github.com/ropensci/rrricanes/blob/master/R/gis.R#L405) func.) So, maybe hopefully, it's an easy fix. I'll try and look at it tonight.

**Comment by timtrice** [comment]
On a side note, and maybe this should be addressed elsewhere other than this issue. It is becoming increasingly clear the NHC website is unreliable for this package. 

What is the consensus on building something like a mirror-site that would hold the raw data this package accesses rather than directly through the NHC? 

If I should post this elsewhere, please let me know.

Thanks

**Comment by sckott** [comment]
Thanks for the quick response. For this post, I could see if it's feasible to use output you had already created in your rendered version and see if that will work - so we can get it up today. 

Good question on the data, Discussion forum https://discuss.ropensci.org/ would be a good place for that. will chime in there

**Comment by timtrice** [comment]
Yea, if that works for you guys it works for me. I hate putting something up that technically isn't working but if my suspicion is correct then it can be resolved fairly quickly.

**Comment by sckott** [comment]
okay, thanks

**Comment by sckott** [comment]
Okay, just made a replacement fxn for `gis_wsp` that works for the blog post

however, also getting an error on the `gis_latest()` call

```r
gis <- gis_latest()
#> Error in stringr::str_match(shp_files, "^(.+)\\.shp$")[, 2] : 
#>   subscript out of bounds
```

traceback() gives

```r
7: eval(lhs, parent, parent)
6: eval(lhs, parent, parent)
5: stringr::str_match(shp_files, "^(.+)\\.shp$")[, 2] %>% stringr::str_replace_all("[[:punct:][:space:]]", 
       "_")
4: .f(.x[[i]], ...)
3: .Call(map_impl, environment(), ".x", ".f", "list")
2: purrr::map(gis_zips, gis_download)
1: gis_latest()
```

thoughts?

**Comment by timtrice** [comment]
@sckott, 

Sorry to get back to you so late. You can hold off on publishing for now if it's not too late. I haven't had a chance to look at the other error and I suspect this one is likely similar. But I honestly have no idea off the top of my head.

**Comment by sckott** [comment]
if you don't mind I’ll go ahead with it and just not run that chunk with the call to `gis_latest`

**Comment by timtrice** [comment]
That will work and I'll do what I can to get it resolved today

**Pull request merged**
