### PR TITLE
Added Dan's blog post

### PR DESCRIPTION
**Pull request by karthik**
It's ready to go and I can post it today if there are no objections. 
@danielskatz @cboettig

### CODE REVIEW

**Comment by danielskatz** [comment]
let me post it on my site first, with cross-links...

give me a few minutes.

**Comment by karthik** [comment]
Sure, just give me a thumbs up here and I'll post.

**Comment by danielskatz** [comment]
I've posted this on https://danielskatzblog.wordpress.com/2016/05/25/software-sustainability-research-with-ropensci/ and I've added at the bottom:

"(Note: this is cross-posted on danielskatzblog.wordpress.com and rOpenSci)"

danielskatzblog.wordpress.com links to https://danielskatzblog.wordpress.com/2016/05/25/software-sustainability-research-with-ropensci/

And I will update rOpenSci to link to the right place, once you tell me what that is.

Can you add this to the rOpenScin version too?

Otherwise, it's good to go.

**Comment by karthik** [comment]
Here's our link: http://ropensci.org/blog/2016/05/25/software-sustanability-ropensci

**Comment by danielskatz** [comment]
thanks - I've updated my version now.

**Comment by danielskatz** [comment]
Can you add my middle initial "S."?

**Comment by karthik** [comment]
Done and updated.

**Comment by danielskatz** [comment]
found a typo - at the end, please change "since this is way that open source" to "since this is the way that open source"  (add "the" before way)

**Comment by karthik** [comment]
Fixed.

**Comment by danielskatz** [comment]
thanks - I hope that's everything...

**Pull request merged**
