### PR TITLE
add bikedata draft blog entry

### PR DESCRIPTION
**Pull request by mpadge**
## Blog post? - yep

> See https://raw.githubusercontent.com/ropensci/roweb/master/_posts/2017-04-11-assertr.md
to copy and paste the yaml header we use - changing to your details
of course. Please include a link for you (e.g., your website or
GitHub profile) in the "url" field.

whoops, haven't got a link yet, but will do that. Don't accept the PR yet - I just wanted to let you know I'm fully onto it and all over it

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Please ping Scott and me here and/or on Slack later when you're ready for feedback.

**Comment by mpadge** [comment]
One pre-emptive Q: Length? I'm thinking of cutting most of the messy code in the current, penultimate "visualisation" bit, and replacing it with a few descriptive lines. That'd make the whole thing quite short. I'm suspecting short is likely not a bad thing - avoids reader tune-out and all - but could readily extend with some more flowery prose if a bit more length was preferred. Brief thoughts @stefaniebutland @sckott?

(And @stefaniebutland: My delay in doing this was coz of waiting for the CRANification of [`dodgr`](https://github.com/gmost/dodgr), which only appeared today! :champagne: helps write a much better post, methinks.)

**Comment by sckott** [comment]
- length: i'd be in favor of shortening viz section
- can you change all `ROpenSci` to `rOpenSci`
- i assume you're planning to add yaml metadata to top of post?

**Comment by stefaniebutland** [comment]
@mpadge I know this is a draft but since you opened the door ;-) I have comments that I hope are helpful

- in your intro I would lead with something like the bikedata para indicating it provides access to data to which users may already have directly contributed, rather than spending 2 paras talking about what other packages don't do - you can put that after
- I like the "science of cities" hook 
- in the case of this pkg, it's important to explain why it makes sense within rOpenSci scope
- the gender comparison example made me pause. Here's where you have to forgive me for commenting on an early draft. You show a statistically significant difference between women and men for average distance but I'm wondering whether there is a practical significance. It's cool to illustrate this comes from millions of data points, but is there meaning to be gleaned from this example in this blog post? If there is, it should be clearly laid out to avoid appearing to arbitrarily choose gender for comparison and leaving readers to infer meaning. If it's just a cool example, is there another you could choose?
- near end, can you please acknowledge reviewers with link to their GitHub or twitter - whichever seems best for each
- consider linking to your pkg review, https://github.com/ropensci/onboarding/issues/116
- *awesome* that you added a Hacktoberfest tag to an issue - rOpenSci will encourage this
- pasting practical notes here from your onboarding issue
  - for yaml metadata: https://github.com/ropensci/roweb/blob/master/.github/CONTRIBUTING.md
  - suggested tags: R, community, software, review, onboarding, package, package_name, topic labels used in onboarding review

Thanks a heap for doing this! Hope it gets more eyes on your work.

**Comment by mpadge** [comment]
okay @stefaniebutland @sckott, this should now be in a fairly decent form. Any and all feedback welcome - please be as critical as you want! Stefanie, I've replaced the gender analysis with a more generic "member/non-member" distinction. Funny thing was I had thought the gender one would have worked out the opposite way, and had what I thought was a rather funny yet totally PC claim about gender differences to interpret it. It didn't work out that way, and so I couldn't, and as you are well aware, it's ultimately better just to leave such prickly issues alone.

But now note that I've not really done any interpretation of the results at all. I could add a bit extra, but it's likely to be so highly speculative using these data alone that i doubt it would bring much. I've left it in the current form in the conviction that it's okay in a blog entry merely to show the kind of results that can be extracted, and to leave actual interpretation for other times/people/fora. If either of you disagree, I'd be totally happy to add a bit more exploratory code.

**Comment by stefaniebutland** [comment]
Thank you @mpadge ! I'll have another look early next week (or sooner depending in my to-do list)

**Comment by stefaniebutland** [comment]
@mpadge ok, I'm much later than I thought/ hoped. I'll look at this Mon 16th AM, Pacific time. Sorry for the delay

**Comment by mpadge** [comment]
no worries - i'll have some time later on (my) tonight, which'll be your late afternoon, in case you desire any particular changes. An alternative would be for you to accept the PR, the re-commit any editorial interventions you see fit, and I can simply approve (or not, but hopefully that wouldn't be necessary).

**Comment by stefaniebutland** [comment]
@mpadge This post reads beautifully!!! With these revisions you make your case very well for people to use and contributing to the pkg. Once the post is up I'll send a handful of tweets from rOpenSci, so please RT etc from there. R-weekly picks up our posts & tweets very quickly (which is awesome) but of course we prefer to have the traffic go our way.

Pinging @sckott here to check for any technical issues.

**Pull request merged**
