### PR TITLE
draft blog post for Community Call v12

### PR DESCRIPTION
**Pull request by stefaniebutland**
Scott, Karthik, This is meant to be a blog post to introduce the next Community Call. Appreciate any comments/edits.
Improve the topic name?
Are the tags appropriate?
I'm waiting for Safia's title and for Titus to approve his bio.

### CODE REVIEW

**Comment by sckott** [comment]
just fyi, you can mention people with their github user name e.g,. `@sckott` and they will get email ping or whatever notifications they get

**Comment by sckott** [comment]
for tags you can have a look at our current tags https://ropensci.org/tags.html - been meaning to consolidate those to reduce redundancies, etc., but haven't quite done yet

**Comment by sckott** [comment]
Looks good to me, nothing I can think to change at this point

**Comment by stefaniebutland** [comment]
@karthik can you please check this draft post for Comm Call Dec 15 (and the associated google doc, Comm Call issue)?

Suggestion for a better title?

**Pull request merged**
