### PR TITLE
draft blog post on rOpenSci team at conferences

### PR DESCRIPTION
**Pull request by stefaniebutland**
Plan is to do a post like this every 2-3 months.  
Please add relevant meetings in comments and I will include before posting Wed Nov 9, 3PM. Suggestions to improve intro para text, structure, (anything!) appreciated.

### CODE REVIEW

**Comment by sckott** [comment]
looks good to me @stefaniebutland

**Comment by jennybc** [comment]
I will also be at Plotcon next week:

https://plotcon.plot.ly

**Comment by cboettig** [comment]
looks good to me; no travel plans to add.

**Comment by jeroenooms** [comment]
Too bad I just came back from two conferences :( Planning to focus on development the upcoming months.

**Comment by karthik** [comment]
@stefaniebutland Looks great! Only comment is `Kissimmee, US` could be `Kissimmee, FL, US` since people outside Florida might not recognize the city. But that's just a minor suggestion. You can choose to ignore it.

**Pull request merged**
