### PR TITLE
Package internetarchive on CRAN

### PR DESCRIPTION
**Pull request by lmullen**
This commit adds the link to CRAN.

### CODE REVIEW

**Comment by sckott** [comment]
@lmullen do you have a vignette ready?  if so, we can get a tutorial up for this pkg

**Comment by lmullen** [comment]
@sckott Yes, there's a vignette in the package: http://cran.rstudio.com/web/packages/internetarchive/vignettes/internet-archive.html

**Comment by sckott** [comment]
@lmullen thanks

**Comment by lmullen** [comment]
@sckott Thanks. Feel free to let me know if you want me to write anything up.

**Comment by sckott** [comment]
pushing a first version in a minute

**Comment by sckott** [comment]
@lmullen does this look okay? http://ropensci.org/tutorials/internetarchive_tutorial.html

**Comment by lmullen** [comment]
@sckott This looks great. Thanks for putting it together, and for taking the `eval = FALSE` flags off. (Those were necessary in order to get the vignette build time down for CRAN.)

Perhaps the phrase "Stable version from CRAN" should be a sentence? "You can install the stable version of the package from CRAN." Up to you.

**Comment by sckott** [comment]
Right, sentences! i always forget

**Comment by lmullen** [comment]
I don't mean to be pedantic. I just happened to be replying to this issue
in the midst of grading essays. :-)

On Tue, Mar 24, 2015 at 9:26 PM, Scott Chamberlain <notifications@github.com

**Comment by sckott** [comment]
it's good quality :heavy_check_mark:  is great

**Pull request merged**
