### PR TITLE
[WIP] tesseract post

### PR DESCRIPTION
**Pull request by jeroenooms**
Post about tesseract and OCR in general. Work in progress.

### CODE REVIEW

**Comment by stefaniebutland** [comment]
Nice clear post, especially outlining key issues. 
Clarifying language:
- change "approximately the double resolution" to "approximately double the resolution"
- change "Running this example in R will show that the accuracy of the first image" to "Running this example in R will show that the accuracy of text extraction from the first image"

End of post:
- add a closing statement to indicate completion/in development status of tesseract in context of "Development is mostly driven by user feedback." Let people know you want feedback? or not?
- Look back at "next version of the package will make this a little easier." and clarify in light of the closing statement

Impact of having Tesseract in R:
- Can you give an example in intro of a specific research project/use case that would be enabled by this? i.e. If someone considering funding rOpenSci read the intro paragraph they would see big, broad impact of the work you/we do. Also gives researcher a glimpse of impact. Power of OCR is obvious but why is it key to have in R?
- another intro comment to come...

**Comment by stefaniebutland** [comment]
Suggestion for beefing up the intro:

Optical character recognition (OCR) is the process of extracting written or typed text from images such as photos or scanned documents. This can be useful for automated text processing of documents that are not available in digital form, such as books or articles or public records. The new rOpenSci package tesseract brings one of the best open-source OCR engines to R. This enables X Y Z. (here give an example of a specific research project/use case that would be enabled by having tesseract in R)

People looking to extract text and metadata from pdf files in R should try our [pdftools](https://ropensci.org/blog/blog/2016/03/01/pdftools-and-jeroen). 

Then 

Getting Started
The package links to the ...

**Comment by stefaniebutland** [comment]
Please add phrase "in the example below" or "in the code below" here:
"The high quality image **in the code below** has approximately double the resolution of the low quality image. "

On first read, it had me looking above at the wikipedia screenshot rather than below to see both files were right there

**Comment by stefaniebutland** [comment]
@karthik please review and give the go-ahead for the post

**Comment by jeroenooms** [comment]
OK I have updated the post with comments from Stef. I think this is good to go.

By the way next time please feel free to just commit your suggestions directly to the PR, or take the lead in the editorial process. No need to keep going back and forth with suggestions. I rather spend my time coding 🤓

**Comment by karthik** [comment]
@stefaniebutland I'm done with edits and pushed a few changes. Take a look and see what you think.

@jeroenooms Apologies. I was the one that suggested Stefanie provide comments and feedback inline since she's still getting up to speed with Git and this would be her first time adding directly to a PR.  We'll work with her to streamline edits in the future. Onwards!

**Pull request merged**
