### PR TITLE
Adding webrockets runconf17 blog post and 2 associated images.

### PR DESCRIPTION
**Pull request by MilesMcBain**
## Description
Added .md render of our .Rmd file, created an image folder with our images, updated image links

## Blog post?
The instructions here didn't quite match https://github.com/ropensci/roweb/blob/master/.github/CONTRIBUTING.md which was sent through by Stef. I went with what was in the link.

### CODE REVIEW

**Comment by MilesMcBain** [comment]
I just noticed that one of our images in on the large side - 3.1mb. We could host externally or try to shrink it down if you need.

**Comment by stefaniebutland** [comment]
@sckott This post is to go live Wed July 5th. 
Can you please respond to Miles' comment above about large image? 
@jeroen has agreed to do merge and render while you're away. Jeroen do you have everything you need to do this?

**Comment by sckott** [comment]
Looking at  post now, will comment on anything I see. 

@jeroen just need to add an entry in the yaml header with `topicid: XXX`, where XXX is the topic id in the slug from our forum - just create a new post like https://discuss.ropensci.org/t/packagemetrics-helping-you-choose-a-package-since-runconf17/759 - and use that number at the end of the URL in the yaml of the blog post - then that's it

**Comment by sckott** [comment]
awesome work @MilesMcBain @AliciaSchep 

I don't think the big image is a problem - not sure the emoji will come through though

* Maybe change bottom image to be a bit bigger - hard to see that there's a plot updating there,
 e.g., ``
* twitter handle links near bottom change to `([@aliciaschep](https://twitter.com/AliciaSchep),
[@milesmcbain](https://twitter.com/MilesMcBain))`

**Comment by AliciaSchep** [comment]
For emoji, can we replace the :emoji: syntax with a link to the image, e.g.` :smile:` :smile: is ``  ?

(I'll also note that there are emoji plugins for jekyll if you want everyone to be able to use emojis seamlessly in their blogposts... :grin: )

**Comment by MilesMcBain** [comment]
Right so it would become: `` I'll make a commit.

**Comment by MilesMcBain** [comment]
Rocket image looked good on my local preview.

**Comment by stefaniebutland** [comment]
@jeroen Can you please make this post dated Wed July 5, 2017 live ... at your timezone convenience?
When posted, please ping me on slack and I'll tweet it.

Thank you @MilesMcBain and @AliciaSchep !!!

**Comment by AliciaSchep** [comment]
thanks @MilesMcBain! I also had included two other emojis in as well, any chance you could either add the link to those or just remove?  there was a `:smile:` and a `:tada:`.  (Or is there a way I can edit the pull request? Happy to make the change myself, but I think I may need access to your fork of this repo)

**Comment by MilesMcBain** [comment]
I'm hesitant to include fixed size images into the middle of the text, wrapping weirdness etc?
Could replace :smile: with lofi acsii version? :Tada: might have to go.

**Comment by AliciaSchep** [comment]
Good point @MilesMcBain!  I removed or ascii-ified the in text ones.

**Comment by jeroen** [comment]
This is now live @stefaniebutland

**Pull request merged**
